### ISSUE TITLE
Move FAQ to a seperate page

### ISSUE THREAD

**Issue by stevep2007** [GDEED/RV_Root#107]
Adding the FAQ to the About page makes it heavy and too dense. The FAQ would be easier to find if it were on a list under the About navigation item.

**Comment by mcclaskiem** [comment]
@Rjected Are you able to make this switch? If so, let me know if you have any questions!

**Comment by stevep2007** [comment]
here are some additions @Rjected to add to the FAQ

**Do you have my application? I didn’t receive an email confirmation.**
When your application form goes through you will receive a confirmation of transmission on the website that reads:  “Thank you for your submission!  We’ll keep you posted”  You will not receive an email.

**Do I need to resubmit my application form again or just the resume?**
Do not resubmit your application form. Just email your resume to us as an attachment. We will match it with your application. Please email your resume to team@realityvirtuallyhack.com using the same email included with your application.  And please include your name in the filename of the resume.  

**Do I have to submit a resume to be considered?**
Including a resume is optional
