### ISSUE TITLE
Website thumbnail resolves to GDG thumbnail - replace with Reality Virtually thumbnail

### ISSUE THREAD

**Issue by stevep2007** [GDEED/RV_Root#108]
This is what resolves on Twitter.

![image](https://user-images.githubusercontent.com/3673316/47674685-45577a80-db8e-11e8-9abe-5a9800f78833.png)

**Comment by mcclaskiem** [comment]
@stevep2007 I just tested the site using Twitter's card validator and the Facebook Object debugger and both are working as expected, screenshots below:
![screen shot 2018-10-29 at 3 40 26 pm](https://user-images.githubusercontent.com/6970287/47675811-505fda00-db91-11e8-81b7-406c661e6afa.png)
![screen shot 2018-10-29 at 3 43 04 pm](https://user-images.githubusercontent.com/6970287/47675836-6077b980-db91-11e8-8d34-6eb0e6fa017f.png)
