### ISSUE TITLE
Add a check box for student and Wayray to the AR/VR Experience on application page

### ISSUE THREAD

**Issue by stevep2007** [GDEED/RV_Root#120]
Coordinate with Murali to write to the spreadsheet. 

Add a checkbox "I am currently a student" after the last name field.

Add the category WayRay to the AR/VR Experience

**Comment by cwrage77** [comment]
Not the prettiest check box but its there and working, please verify.

**Comment by mcclaskiem** [comment]
@stevep2007 Can you confirm the new checkbox and new options for AR/VR Experience. Thanks!
