### ISSUE TITLE
Fix "About" Navigation bar item

### ISSUE THREAD

**Issue by stevep2007** [GDEED/RV_Root#124]
The About item in the navigation bar is linked to the About page. It is not intuitive to click on the nav bar item when there is a sub item like the FAQ that we have below and will have the sub item Schedule. 

The link to the About page should be removed from the About item in the navigation bar and moved to a sub-item like we did last year, depicted in the image below

![image](https://user-images.githubusercontent.com/3673316/48068803-d12a6180-e1a1-11e8-8d86-13a75f03876d.png)

**Comment by mcclaskiem** [comment]
I think having two nav items with "about" in the text is redundant. The current approach is pretty standard on the web and will ensure the nav does not get too big on mobile since everything is already pre-expanded in the mobile drawer.
