### ISSUE TITLE
Homepage: less(trim it to half) text for hackathon on the 3 pillars

### ISSUE THREAD

**Issue by JennaOlander** [GDEED/RV_Root#132]

**Comment by cwrage77** [comment]
Any suggestions for the trim?

**Comment by stevep2007** [comment]
I would really like to cut down the text for the homepage on the Hackathon section in the three pillars right now it is currently:

The biggest immersive hackathon in the world is in the works. During a full five days, you will meet new people, form interdisciplinary teams, brainstorm and build AR/VR experiences and applications that redefine immersive technologies. We will have passionate and skilled mentors to help teams ideate, build and deliver their projects. Vetted and qualified judges will pick the best among a variety of categories. Sponsors will provide an abundance of technology platforms to work with: ARCore, ARKit, Vive, Gear VR , Hololens, and more.

Can we cut it down to this?

During a full five days, you will meet new people, form interdisciplinary teams, brainstorm and build AR/VR experiences and applications. There will be very skilled mentors to help out along the way. Sponsors will provide an abundance of technology platforms to work with: ARCore, ARKit, Vive, Gear VR , Hololens, and more.

**Comment by cwrage77** [comment]
Updated -
