### ISSUE TITLE
Homepage: @ MIT media lab

### ISSUE THREAD

**Issue by JennaOlander** [GDEED/RV_Root#133]
Perhaps make this a link for the address and make this the same text size as the date. Just underline please

**Comment by cwrage77** [comment]
Did some custom work for this to work, changing it to a link puts the "dark with highlight" kind of effect on it. Was able to get it as a link to the map section, however, no underline is possible because the one active is really huge . Check it out, it was a good addition.

**Comment by JennaOlander** [comment]
Looks great! 
Thank you for doing that. would it be possible to make it the same text size as the dates as well?

**Comment by cwrage77** [comment]
Resized

**Comment by cwrage77** [comment]
Closing
