### ISSUE TITLE
FAQ page Spacing

### ISSUE THREAD

**Issue by JennaOlander** [GDEED/RV_Root#134]
Please reduce the spacing between all Questions- also, could someone please make the questions H2 instead of H1? just to make the text size smaller :)

**Comment by cwrage77** [comment]
They are actually oversized h4s currently, I can shift them to h2. Some of the spacing is defined by the animation, will test around.

**Comment by JennaOlander** [comment]
![screen shot 2018-11-14 at 8 38 07 pm](https://user-images.githubusercontent.com/42751973/48524160-40acea80-e84d-11e8-95a2-7f281e63843e.png)

**Comment by JennaOlander** [comment]
please meake them the same size as "team foundation" in the schedule

**Comment by cwrage77** [comment]
Added class to match requested

**Comment by cwrage77** [comment]
Closing
