### ISSUE TITLE
Make highlighted parts green

### ISSUE THREAD

**Issue by JennaOlander** [GDEED/RV_Root#135]
![screen shot 2018-11-14 at 8 48 20 pm](https://user-images.githubusercontent.com/42751973/48524543-b4032c00-e84e-11e8-8609-df7700350ad7.png)
during mouse over it is blue. please make it green (super minor)

**Comment by cwrage77** [comment]
Added, was not sure which green to choose - went with #078000

**Comment by cwrage77** [comment]
Closing
