### ISSUE TITLE
Registration Page Corrections and Clarifications

### ISSUE THREAD

**Issue by stevep2007** [GDEED/RV_Root#138]
1.)  Change enroll to register in the URL and change the title from "Enroll for the Hackathon" to "Accepted Reality Virtually Hackathon Participant Registration"

2.) replace "Please uplaod and submit the signed release form" with "Registration must be accompanied with a signed release."

3.) The submission/error popup in the case of an email entry error should include "Your email may be different than the one you used to apply. Please contact team@realityvirtuallyhack.com."

There were a handful of email errors when Maria emailed everyone to fix the race and gender omission. In the case where this has happened the registration will be corrected. 

4.) Change OG and twitter meta resolution when the URL is shared. 

When the URL  is shared we don't want either the OG image currently associated with the page or the text "Enroll for the Hackathon Calling everyone to create, learn and explore new and yet to be known VR and AR applications at the MIT Media Lab, Cambridge, Massachusetts, USA"

The OG text and twitter title and other social media should be "Reality Virtually Hackathon Registration for Accepted Participants."

We can use this image of the OG and twitter image and other social media https://drive.google.com/open?id=18djOyop0fXsEhRwmYpsja9aJQYRk02_5

5.) The text "Mandatory: Upload Release Make sure you sign and upload the Release. This is a madatory step " should be changed to  "You must complete and sign the Reality Virtually Hackathon Release https://docs.google.com/document/d/1nEdxvDFuoMbat0JKzbRdpxuUJwIleZwxLblwpajUNsI/edit?usp=sharing to complete your registration and to participate in the hackathon"

6.) "What is your current location?" should be changed to "Please enter your complete home/residential address"

Street1
Street2
City
State/Province/County
Postal Code
Country (nice if this were a drop down)

7.) "Do you require childcare?" should be changed to "Would childcare enable you to attend the hackathon?"

**Comment by stevep2007** [comment]
**Correction**

delete the field "What is your current location?"

and change "What is your Residential address? (Address, City, State, Country, Zip)" to "Enter your postal address, city, state/county, country and postal code"

**Comment by stevep2007** [comment]
disambiguate the Release Upload Confirmation

When the release is uploaded this confirmation is displayed

![image](https://user-images.githubusercontent.com/3673316/48633120-a6ee5600-e990-11e8-9a30-433d393ae122.png)

This might confuse the person to believe that they have completed their registration. 

There are two possible ways to fix it. 

1.) Eliminate the two steps, Load Release followed by submit application. After the release is selected just have the one button Submit Registration

2.) If it cannot be changed to one button, then after the Load Release button is pressed there should be a loading icon while the document is uploaded, and change the confirmation that is displayed to:

Nice!
Your have successfully uploaded the release form
Go on to submit the registration information to complete your registration

**Comment by stevep2007** [comment]
The text in the button "Submit Application" Should be changed to Submit Registration"

**Comment by stevep2007** [comment]
Here are Seha's comments


I filled the form, doesn't give an alert message if the e-mail is not in e-mail format, like using "@" sign. If we add formatting for phone number it might be good as well instead of leaving it blank. 

_Steven Comment_ if we regex the telephone it should support international formats. 

Also, you can leave empty almost all fields which I think it should not happen. I entered any text to both email and phone # and i was allowed to submit the form

**Comment by mcclaskiem** [comment]
@stevep2007 Just made the following changes, some of the other tasks I may need help from @prathmesh-j and team

Fixed 1,2,5,6,7
Fixed Alert for release upload
Deleted Current Location
Made all fields required
