### ISSUE TITLE
Billing Problem

### ISSUE THREAD

**Issue by cwrage77** [GDEED/RV_Root#146]
We are having a problem billing your account. Please enter a new payment method or check with your payment provider for details on why the transaction failed. If you don’t need access to your private repositories, you can downgrade to the Free plan in your Billing settings.
You can always contact support with any questions.

**Comment by stevep2007** [comment]
@cwrage77 Would you please tell me where  I find this message?

**Comment by cwrage77** [comment]
Hey Steve, I copy pasted that message from the current view of the repo. However, I think I was mistaken and its actually tied to My own billing for github haha :) sorry for confusion, disregard. If this message does come up btw (it will be on this current page and all others.

<img width="1363" alt="screen shot 2018-11-22 at 1 17 35 pm" src="https://user-images.githubusercontent.com/10321212/48918173-03ea8000-ee59-11e8-9b89-790b13ed1168.png">
