### ISSUE TITLE
User cannot register for the hackathon

### ISSUE THREAD

**Issue by stevep2007** [GDEED/RV_Root#149]
The user with the email lkwatson@bu.edu cannot register for the hackathon. I just confirmed that the error
Error!
Your email may be different than the one you used to apply. Please contact team@realityvirtuallyhack.com.

Would you please check why this is happening

**Comment by prathmesh-j** [comment]
Fixed. The script was not updated. I just updated the column range for validation.

**Comment by cwrage77** [comment]
Closing as per note above - please reopen if issue persists.
