### ISSUE TITLE
Document the additions of emails for compare on registration page

### ISSUE THREAD

**Issue by stevep2007** [GDEED/RV_Root#154]
To enable other devs to add to the email list used to check the registrant's email the steps need to be documented in the directory  https://drive.google.com/open?id=10yUIHmOQv067HXus7yqE787rv-b05PXq and the rest of the devs notified on slack.

**Comment by prathmesh-j** [comment]
I am not able to create a new file in the link provided above. I am describing the process below.
So the verification of emails and getting the additional details from the selected applicants basically uses 2 google sheets.

***Phase 2 Finalists*** - https://docs.google.com/spreadsheets/d/1hTQ1aLp2jkjTKvFDuNkSlbfr-MNSnOPHQiLU7fHDlT4/edit?pli=1#gid=0
***Phase 2 Applicants*** - https://docs.google.com/spreadsheets/d/19IjE00XS6zTPAebbxZSQlXE3rLGCKsnisgKhSmgBu1w/edit#gid=0

So if a new application is selected, the email and name needs to be added in the _Phase 2 Finalists_ sheet.
Once this is done, any dev can log in to the script and update the rows for scanning the emails from the list. The script can be found here

***Script for verifying email*** - https://script.google.com/a/macros/realityvirtuallyhack.com/d/M1gK4z3szoE9s20Wjbc5BIPuHtjn7o6ly/edit?uiv=2&mid=ACjPJvEDOTcoyj7onDNxMFTnSXpho3gJkZ-HoR9NADfI2zNq3gAun-jtn7VBkvAojAN-vXbLo96JLptlyFMktkyPWrm9SP9FmJA44uFTXeSyDVyt8iDdMlB6PmdOpqAgN6cWQr0d0j9BjgIo&pli=1

Currently on ***Phase 2 Finalists*** the last non empty value is _C:204_. So make sure the ***Script for verifying email*** has the same value


Note - Use participantmtg@realityvirtuallyhack.com account for everything

**Comment by prathmesh-j** [comment]
Added description
