### ISSUE TITLE
Add Blog Page

### ISSUE THREAD

**Issue by stevep2007** [GDEED/RV_Root#158]
Please add blog page

We'll get the first blog entry to you early next week. This is very important because we will announce Magic Leap sponoship and participation at the hackathon with 10 of their headsets. 

@Seguda should be able to update with new entries.

**Comment by cwrage77** [comment]
@stevep2007 The blogging functionality is already built and supported by the framework. It is currently live at https://realityvirtuallyhack.com/blog/ (the list) and if you click the post you can get the individual ones in page form.

@Seguda The way to add and manage them is by creating md files in this location https://github.com/GDEED/RV_Root/tree/master/_posts in the form of markdown files. The 4 active were kept for sample purposes but should be removed as soon as possible.

As it stands we're kind locked to the power of mark down, which will look great. Please respect the naming convention of the files and test locally before pushing.
