### ISSUE TITLE
Update Email Database for Registrations

### ISSUE THREAD

**Issue by stevep2007** [GDEED/RV_Root#163]
The database of email addresses to be compared needs the latest update. Here are the accepted and the the updated emails in red.

https://docs.google.com/spreadsheets/d/1PeTs3D2qmafDaGphyZaCR8hn79Gz0RArXSfx92iVxk8/edit#gid=1736598341

**Comment by cwrage77** [comment]
What needs to be done here? Everyone has full read and write privilege on these documents, let me know how i may assist @prathmesh-j
