### ISSUE TITLE
Registration Email Verification Uptate Docutmention and Updates on November 30, 

### ISSUE THREAD

**Issue by stevep2007** [GDEED/RV_Root#164]
**please do not close this issue until after January 17, 2019 **
@cwrage77 

This documentation issue **Document the additions of emails for comparing on registration page #154
was** closed by @prathmesh-j  so you did not see it. It should not have been closed because this procedure will need to be performed on December 15, 2018, December 31, 2018 and January 10, 2019.

This is really important - we are two days late sending out the notifications. PJ could do to meet our November 30th deadline but he will be home in India during the next update and notification date December 15 th. Given the time zone and distance, it would be better if Pablo followed these instructions to verify the update process before PJ leaves on December 3 in case there is an error or omission is the documentations. 

=====  @prathmes-j's Documentation on Email Verification Update =======
I am describing the process below.
So the verification of emails and getting the additional details from the selected applicants basically uses 2 google sheets.

Phase 2 Finalists - https://docs.google.com/spreadsheets/d/1hTQ1aLp2jkjTKvFDuNkSlbfr-MNSnOPHQiLU7fHDlT4/edit?pli=1#gid=0
Phase 2 Applicants - https://docs.google.com/spreadsheets/d/19IjE00XS6zTPAebbxZSQlXE3rLGCKsnisgKhSmgBu1w/edit#gid=0

So if a new application is selected, the email and name needs to be added in the Phase 2 Finalists sheet.
Once this is done, any dev can log in to the script and update the rows for scanning the emails from the list. The script can be found here

Script for verifying email - https://script.google.com/a/macros/realityvirtuallyhack.com/d/M1gK4z3szoE9s20Wjbc5BIPuHtjn7o6ly/edit?uiv=2&mid=ACjPJvEDOTcoyj7onDNxMFTnSXpho3gJkZ-HoR9NADfI2zNq3gAun-jtn7VBkvAojAN-vXbLo96JLptlyFMktkyPWrm9SP9FmJA44uFTXeSyDVyt8iDdMlB6PmdOpqAgN6cWQr0d0j9BjgIo&pli=1

Currently on Phase 2 Finalists the last non empty value is C:204. So make sure the Script for verifying email has the same value

Note - Use participantmtg@realityvirtuallyhack.com account for everything

**Comment by mcclaskiem** [comment]
@stevep2007 Can this be closed now?
