### ISSUE TITLE
Day 5 Location Correction

### ISSUE THREAD

**Issue by stevep2007** [GDEED/RV_Root#166]
Please change the address of the Exposition and the Public Expo on https://realityvirtuallyhack.com/schedule/

From: MIT Building 32, Stata Center 32 Vassar Street, Cambridge, MA 02139

to 

MIT Media Lab - 75 Amherst Street, Cambridge, MA 02139

**Comment by cwrage77** [comment]
Updated - see commit for reference for the future.
