### ISSUE TITLE
Update Prize Categories on the 

### ISSUE THREAD

**Issue by stevep2007** [GDEED/RV_Root#170]
About Page

The section called Prize Categories should be replaced with two columns

One column will be Hackathon Themes and the second Catagories and Examples

The tabular information to be added is on the Final tab of this sheet: https://docs.google.com/spreadsheets/d/1PFGIkKvOdMfa9-Ugv9Hfj1yDHsSurfxQ5ES-xK9V_L8/edit#gid=801949313

**Comment by cwrage77** [comment]
@Seguda Let me know if you need a hand with this, requires changes to the config.yml as well as the prize_categories.html

**Comment by cwrage77** [comment]
Please verify and resolve, left the styling straightforward
