### ISSUE TITLE
Edits to the FAQ page

### ISSUE THREAD

**Issue by stevep2007** [GDEED/RV_Root#172]
Is this an overnight hackathon?
~~The MIT Media Lab will only be open from 7am-1am Saturday and then will re-open again at 7am on Sunday.~~

**correct**
The MIT Media Lab will only be open from 7am-1am and re-opens again at 7am on Sunday.

~~Where do I sleep?
Because of building policy, we have to close the hackathon during the night. There are Airbnbs and Hostels in Cambridge for participants to take a rest and refresh themselves.~~

Accommodations
Because of building policy, we have to close the hackathon at night. There are [Airbnbs](https://zh.airbnb.com/s/Cambridge--MA/all?s_tag=hGvUGIxM&allow_override%5B%5D=&refinement_paths%5B%5D=%2Ffor_you) and [Hostels in Cambridge](https://www.yelp.com/search?cflt=hostels&find_loc=Cambridge%2C+MA) for participants to take a rest and refresh themselves.  There are many hotels in the area, the closest is a Marriot. Here is a [list of hotels](https://institute-events.mit.edu/visit/where-to-stay) near the institute.

note: Driving in Greater Boston can be difficult. Roads are hard to navigate, traffic is as abundant as can be found in Los Angeles, free street parking is limited and parking lots are expensive.

**Comment by cwrage77** [comment]
Updated
