### ISSUE TITLE
Format of the Sponsor Page

### ISSUE THREAD

**Issue by stevep2007** [GDEED/RV_Root#187]
The logos should get progressively smaller with each level.

The levels are

MIT Media Lab

Founding Sponsors

Platinum

Gold

Silver

Bronze

Community sponsors (Same size as Bronze)

Hospitality, Food and Beverage (Same Size as Bronze)

**Comment by ChengshiZhang** [comment]
Should MIT Media Lab be listed under the "Founding Sponsors" category like last year's sponsor page, just with a bigger logo?
