### ISSUE TITLE
Add Email Addressed to Registration Compare Sheet

### ISSUE THREAD

**Issue by stevep2007** [GDEED/RV_Root#192]
Here are the emails to add to the sheet used by the registration system for comparing legitimate accepted applicants. 

https://docs.google.com/spreadsheets/d/1PeTs3D2qmafDaGphyZaCR8hn79Gz0RArXSfx92iVxk8/edit#gid=1457934979

**Comment by cwrage77** [comment]
The 'Phase 2 Finalists' sheet was updated some time ago can be verified on the document.

Currently at 519/999 as left preconfigured by @prathmesh-j
