### ISSUE TITLE
Photo and Bio of Alexander Laiman

### ISSUE THREAD

**Issue by stevep2007** [GDEED/RV_Root#213]
Title: MIT AR/VR Community Lead
![alexander laiman](https://user-images.githubusercontent.com/3673316/50544019-428cfc00-0bb6-11e9-8f06-59a03b164035.jpg)

Alexander is an experienced undergraduate researcher at the MIT Media Lab with a demonstrated history of working in Unity. He is also skilled in Photography, Python (Programming Language), C++, and VR development, He is the president of President of VR/AR MIT.

**Comment by Seguda** [comment]
Could you please tell me who is Alexander Leiman?  Is he one of the team members? He was not in the team members reorder list so I didn't add him. 
@stevep2007

**Comment by stevep2007** [comment]
@Seguda Alexander is one of the team members and should be on the team page. Please replaced Dan Cline's entry with Alexander
