### ISSUE TITLE
Add Navigation List Title - Details

### ISSUE THREAD

**Issue by stevep2007** [GDEED/RV_Root#221]
Please add the Navigation List Tittle - Details that will include

FAQ <move from About>
Rules <move from About>
Workshops coming soon Cindy
Location  @stevep2007  to write specification.

**Comment by mcclaskiem** [comment]
@stevep2007 Where should we put "Mentors"?

**Comment by stevep2007** [comment]
Thanks Max, we were diverging from what we did last year. 

How is this for navigation?
![image](https://user-images.githubusercontent.com/3673316/50659141-a96d3500-0f69-11e9-9581-1e43d33a70dc.png)

**Comment by mcclaskiem** [comment]
@stevep2007 Do we still want sponsors underneath about or should we leave as their own nav item?

**Comment by stevep2007** [comment]
@mcclaskiem Sponsors should be their own top level item.
