### ISSUE TITLE
New Blog Post

### ISSUE THREAD

**Issue by stevep2007** [GDEED/RV_Root#224]
[H1 Invitation to the Greater Boston Medical Community to participate in the Reality Virtually Hackathon.docx](https://github.com/GDEED/RV_Root/files/2722072/H1.Invitation.to.the.Greater.Boston.Medical.Community.to.participate.in.the.Reality.Virtually.Hackathon.docx)
 
Please us this image at the top centered. https://www.vectorstock.com/royalty-free-vector/medicine-symbol-vector-2742468

**Comment by Seguda** [comment]
@stevep2007 The image you asked me to add is not free, so I couldn't add it.

**Comment by stevep2007** [comment]
Sorry, I was duped by the representation that this was a free image. 

here is one that is https://commons.wikimedia.org/wiki/File:Caduceus.svg
