### ISSUE TITLE
Remove Rolling admissions on landing page on Monday Jan 7 evening

### ISSUE THREAD

**Issue by stevep2007** [GDEED/RV_Root#230]
Please remove all reference to Rolling Admissions on Monday night Jan 7. As late as you and Max can coordinate the merge. 

Here is what to remove

Rolling Admissions Schedule
Apply by 12/22/18 to be notified by 12/29/18
Apply by 12/29/18 to be notified by 01/05/19
Apply by 01/07/19 to be notified by 01/10/19

We will stop accepting applications except from the MIT community then.

**Comment by stevep2007** [comment]
@mcclaskiem please coordinate the merge of this issue late on Monday night with @Seguda 

Thank you

**Comment by mcclaskiem** [comment]
@Seguda Just send a PR when it is ready and I will merge, thanks!
