### ISSUE TITLE
CTA on Landing Page

### ISSUE THREAD

**Issue by stevep2007** [GDEED/RV_Root#263]
Add a call to action on the landing page

Attend the Public Expo: https://www.eventbrite.com/e/2019-public-expo-for-the-reality-virtually-hackathon-tickets-54512364951

**Comment by mcclaskiem** [comment]
@stevep2007 Should this be on the hero section or do you want this to have it's own section below the fold?

**Comment by stevep2007** [comment]
Hi Max,

That you question this is insightful. 

We will have both the expo on Monday 1/21 and a Community Talks day on Saturday 1/19. We are not done with the Community talks. But if there is room for an Expo CTA and a page with a link to register and in the next day or two to add another hero section for the community talks. Definitely.  

Thank you

**Comment by stevep2007** [comment]
But if there is room for an Expo CTA and a page **with a scrape of the Eventbrite** with a link to register and in the next day or two to add another hero section for the community talks. Definitely.
