### ISSUE TITLE
Wrong link on the winners page for VRFitness

### ISSUE THREAD

**Issue by stevep2007** [GDEED/RV_Root#310]
When the link to VRFitness on the Winners page  https://realityvirtuallyhack.com/winners/  is clicked the Bright Devpost page is displayed. The correct link to VRFitness's devpost page is https://devpost.com/software/vr-fitness
 
![image](https://user-images.githubusercontent.com/3673316/52073031-757b3480-2554-11e9-9c5a-348ad647fd88.png)

**Comment by cwrage77** [comment]
Resolved
