### ISSUE TITLE
Add Schedule Page

### ISSUE THREAD

**Issue by stevep2007** [GDEED/RV_Root#33]
Here is the draft posted to notion. It would be valuable to add as a page by October 1.

https://www.notion.so/rvhackathon/Preliminary-Daily-Hackathon-Schedule-January-17-21-2019-f90fb89a74e548e2994304f63259abd2

@Seguda 
@cwrage77

**Comment by cwrage77** [comment]
Added a sample schedule page @ www.realityvirtuallyhack.com/schedule

Can be configured through _data/schedule.yml
