### ISSUE TITLE
Add about page for Oct 1 release.

### ISSUE THREAD

**Issue by stevep2007** [GDEED/RV_Root#39]
The about section has been edited and approved by the media lab.

Here it is https://docs.google.com/document/d/1P_WXyFLbJ_YFDbQgwV_82lltd_kJQl9pXRz-eEAbgxY/edit?usp=sharing

**Comment by cwrage77** [comment]
I have added the page at https://realityvirtuallyhack.com/about/ holding the data from the document. Still many little fixes to go in regards to styling but the data is there.
