### ISSUE TITLE
Scott Greenwald Bio

### ISSUE THREAD

**Issue by stevep2007** [GDEED/RV_Root#44]
@Seguda 

Scott Greenwald Ph.D.  

Scott is a research scientist in the Fluid Interface Group of the MIT Media Lab. His dissertation on learning and education in virtual reality led to an interest in rapid-prototyping interactions in software making tool development both a byproduct and a focus of his research. He and his team are preparing to release an open-source toolkit for VR research (stay tuned!) Twitter: @scottgwald

**Comment by cwrage77** [comment]
Added
