### ISSUE TITLE
About Page - Replace Images 

### ISSUE THREAD

**Issue by stevep2007** [GDEED/RV_Root#48]
Replace images left of the title **New this year**
Suggestion - Jenna's new logo

Replace the images left of the title **Workshops**
suggestions
https://drive.google.com/open?id=0B0yD6YXrNIE_dTQ5eG1rUGllTWs
https://drive.google.com/open?id=0B0yD6YXrNIE_M3Z3aDNZVTJTTTA

Replace the images left of the title **Mentors**
Suggestion https://drive.google.com/file/d/0B0yD6YXrNIE_Nl9WczRXQ0szWkU/view?usp=sharing

Replace the image left of the tittle **Our Mission and Commitment to Diversity**
I think this should be a small version of Jenna's designs or

Suggestions
https://photos.app.goo.gl/FR81TYofW3HFFjbY7

We have the rights to all the images linked to reproduce and modify

**Comment by cwrage77** [comment]
Not sure about this one, images have max width 250px, we need HD png's preferably.

**Comment by cwrage77** [comment]
Updated Yesterday, picked arbitrary last image.
