### ISSUE TITLE
About Page Winners Project images links

### ISSUE THREAD

**Issue by stevep2007** [GDEED/RV_Root#49]
The three winners displayed in the **2017 Hackathon Grand Prize Winners** section of the **About** page
SpeakEasy
Cosplay
LeapMotion/Cultoure

Should be linked to the Devpost of each project.

An additional line or button **See All Last Year's Winners** should be linked to https://pastevents.realityvirtuallyhack.com/2017-winners

**Comment by cwrage77** [comment]
Configured
