### ISSUE TITLE
About Section Video

### ISSUE THREAD

**Issue by stevep2007** [GDEED/RV_Root#54]
We have two choices of videos that have been finish edited. 

One is 1 minute: https://www.youtube.com/watch?v=jT_ti4HPC8s

The other is the same length as the one posted. https://www.youtube.com/watch?v=yMxWzFRmWAg

Both are higher quality and higher resolution. 

The size of the video seems a little bit large.

**Comment by cwrage77** [comment]
Added video configuration on the config.yml L 93
