### ISSUE TITLE
Sponsor Page

### ISSUE THREAD

**Issue by stevep2007** [GDEED/RV_Root#56]
@cwrage77 

The sponsor page should include only the MIT Media Lab Logo and the three founding sponsors. It should look something like this [mock up image of the sponsor page. ](https://drive.google.com/open?id=177TfIvXuCMgrafr5k1CpMdND7VpBY16L)The reason for the mock up page reference is the Samsung Logo changed since Max created [last years sponsor page](https://pastevents.realityvirtuallyhack.com/sponsors/).

Here is the MIcrosoft Logo https://drive.google.com/open?id=0B6160HuKy-hgSzhDamUzRDVIVEU

Here is the AT&T Logo https://drive.google.com/file/d/0B6160HuKy-hgaGhzOUNGYjY2U2c/view?usp=sharing

Here is the Samsung Next Logo https://drive.google.com/file/d/0B6160HuKy-hgV2ZYdzZyakZwVkw3MVM3ajFsUTVxT18xaGZj/view?usp=sharing

The MIT Media Lab logo is freely available. Let me know if you need me to find one.

**Comment by cwrage77** [comment]
https://realityvirtuallyhack.com/sponsors/
