### ISSUE TITLE
Rus Gant Bio Edit

### ISSUE THREAD

**Issue by stevep2007** [GDEED/RV_Root#81]
@Seguda 

This is as much as I can shorten it. 

Rus Gant is a well-regarded international 3D artist, computer visualization engineer, and educator with four decades of experience in computer visualization, archaeology, and museology. A member of the research staff at Harvard University where he also leads the Visualization Research and Teaching Laboratory. Formerly the lead technical artist for Harvard's Giza 3D project reconstructing the Egyptian monuments on the Giza Plateau in virtual reality. He is on the teaching faculty at Tokyo’s Showa Women's University and a fellow at the MIT Center for Advanced Visual Studies and Carnegie Mellon's  Center for Creative Inquiry. 

Thank you

**Comment by Rjected** [comment]
Closing, Fixed with #83
