### ISSUE TITLE
Cindy Bishop Bio

### ISSUE THREAD

**Issue by stevep2007** [GDEED/RV_Root#82]
@Seguda 

Cindy is the Workshop Lead

Here is her bio:
CINDY SHERMAN BISHOP
Cindy is a multimedia artist and creative coder.  She authored several webVR storytelling tools as a fellow at the MIT Open Doc including VRDoodler, a web-based 3D drawing program that renders in virtual and augmented reality. At the MIT Civic Media Lab on the Media Cloud team, her role as web developer is helping to build the next generation of web-based tools for journalists and researchers

And here is her photo https://drive.google.com/open?id=0BwBS8QIwNRl7Y0lQdkhDcXd6OUk

**Comment by Rjected** [comment]
Closing, fixed with #83
