### ISSUE TITLE
Change application url from realityvirtuallyhack.com/register to realityvirtuallyhack.com/apply

### ISSUE THREAD

**Issue by stevep2007** [GDEED/RV_Root#85]
We are using the url realityvirtuallyhack.com/register for the applications. It could confuse the applicant to believe they were registering instead of applying. 

Please change the URL to realityvirtuallyhack.com/apply. Please also map the old URL realityvirtuallyhack.com/register into => the new URL realityvirtuallyhack.com/apply

**Comment by mcclaskiem** [comment]
Fixed with #84
