### ISSUE TITLE
Reports of Resume's not loading 

### ISSUE THREAD

**Issue by stevep2007** [GDEED/RV_Root#86]
We received 5 emails that resumes were not uploading, stuck with the progress spinner turning. 

I just uploaded and it took 22 seconds. I am connected using a 32GB i7 with 5GHz 802.11C connected to 1GBPS Fios. File size was 2,800 kb. 

@mayyapillai @mcclaskiem

**Comment by mcclaskiem** [comment]
@mayyapillai Does Google Drive allow for streaming uploads?

**Comment by stevep2007** [comment]
@mayyapillai I'm getting a hard failure trying to upload a resume. 

In one case I used a Firefox incognito browser - unauthenticated with Google or any other service and I was unable to upload the resume.

In the second case, I used chrome and was authenticated with Google. 

In the third case I used a Chrome incognito browser and was authenticated using participantmgt@realityvirtuallyhack.com

In all cases I get the spinning wait circle.

**Comment by stevep2007** [comment]
@prathmesh-j  identified the problem - 
Access to XMLHttpRequest at 'https://script.google.com/macros/s/AKfycbytXrHVWPxhx4VJx2XMX_Q17WuQghvV-z1eX3pg_0kvnAbKxDs3/exec' from origin 'https://realityvirtuallyhack.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
register.js:224 xhr.responseText 
VM118:1 Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at XMLHttpRequest.xhr.onreadystatechange (register.js:226)
xhr.onreadystatechange @ register.js:226
XMLHttpRequest.send (async)
UploadFile.reader.onload @ register.js:219
load (async)
UploadFile @ register.js:193
onclick @ (index):1
register.js:219 Cross-Origin Read Blocking (CORB) blocked cross-origin response https://script.google.com/macros/s/AKfycbytXrHVWPxhx4VJx2XMX_Q17WuQghvV-z1eX3pg_0kvnAbKxDs3/exec with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.
