### ISSUE TITLE
Dropdown lists producing application entry errors

### ISSUE THREAD

**Issue by stevep2007** [GDEED/RV_Root#92]
The application form fields listed below should have a blank list element for the first list element instead of the first list element. 

Country of Citizenship
**first list element** AFGANISTAN

How did you hear about the Reality Virtually hackathon?
**first list element** By Email

Preferred/Desired Hackathon Role
**first list element** Developer

AR/VR Experience
Subcategory other **first list element** other

Gender 
**first list element** Female

if ignored the top level list element will be the default and posted to the datastore.  So for Country of Citizenship, it will be Afganistan unless the applicant changes it and the Preferred/Desired Hackathon Role Developer 

Each dropdown list should begin with a blank entry and selection should be mandatory.

**Comment by mcclaskiem** [comment]
Fix in progress.
