### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by JennaOlander** [GDEED/RV_Root#95]
Please create a standard FAQ with the same typeface as the website. Question should be H1 and answer should be H3. It would be great if we could have this on the about page with a top nav FAQ button that directs to to that specific spot on the about page once clicked

**Comment by stevep2007** [comment]
@JennaOlander 

I'm not sure what you mean here _could have this on the about page with a top nav FAQ button that directs to that specific spot on the about page once clicked_

Do you mean the FAQ would be part of the About page or a separate page indexed from the navigation bar?

Should the FAQ utilize the accordion GUI from past years?

**Comment by JennaOlander** [comment]
Would it be possible for it to either have its own page and be on the about (be in two different places on the website) and for us to have it at the top nav?

**Comment by Rjected** [comment]
@JennaOlander We could have it on its own page as well as the about, also I've found that accordion-style FAQ works well when it should be compact.

**Comment by Rjected** [comment]
I've added it to the about page, check the [latest commit to the faq branch](https://github.com/GDEED/RV_Root/commit/e2594373c5579d23fe8319bc46609453753a2d09) to see what it's like. Thoughts?

**Comment by stevep2007** [comment]
@Rjected it looks good to me. Please create a pull request and either @mcclaskiem or @cwrage77 will check and merge. 

There should be a menu item below About for the FAQ that takes the user to the top of the FAQ because the about page has become so long, people may not see it.
